#!/usr/bin/env python3
"""Dump slide text from every carriers/**/*.pptx into extracted/pptx-text.md."""
from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE


def shape_text(shape) -> list[str]:
    out: list[str] = []
    if shape.has_text_frame:
        t = "\n".join(p.text.strip() for p in shape.text_frame.paragraphs if p.text and p.text.strip())
        if t:
            out.append(t)
    if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
        for s in shape.shapes:
            out.extend(shape_text(s))
    return out


def extract(path: Path) -> str:
    prs = Presentation(str(path))
    blocks = [f"# Extract — {path.name}\n", "Generated by tools/extract_pptx.py. Vision carrier, not literature.\n"]
    for i, slide in enumerate(prs.slides, 1):
        chunks: list[str] = []
        for shape in slide.shapes:
            chunks.extend(shape_text(shape))
        notes = ""
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame:
            notes = slide.notes_slide.notes_text_frame.text.strip()
        blocks.append(f"## Slide {i}\n")
        if chunks:
            blocks.append("```\n" + "\n\n".join(chunks) + "\n```\n")
        if notes:
            blocks.append(f"**Speaker notes.** {notes}\n")
    return "\n".join(blocks)


def main() -> None:
    root = Path("carriers")
    if not root.exists():
        return
    for pptx in sorted(root.rglob("*.pptx")):
        dest = pptx.parent / "extracted" / "pptx-text.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(extract(pptx), encoding="utf-8")
        print(f"wrote {dest}")


if __name__ == "__main__":
    main()
